### ISSUE TITLE
How to change upload size?

### ISSUE THREAD

**Issue by heroims** [rolfwessels/docker-simple-nuget-server#6]

**Comment by rolfwessels** [comment]
Are you asking how the change the MAX upload size to the package manager?

If so I believe this line in the docker image is where I set the max upload size to be 20mb
https://github.com/rolfwessels/docker-simple-nuget-server/blob/master/Dockerfile#L27

**Comment by heroims** [comment]
It's not enough. you must add 'post_max_size' in php.

**Comment by rolfwessels** [comment]
:+1: send a pull request if you think other users will find it useful.
